In [1]:
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b=np.array([[1,2],[3,4],[5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
b.ndim

2

In [6]:
b.shape

(3, 2)

In [7]:
b.dtype

dtype('int32')

In [10]:
c=np.arange(10) #等差
print("c=",c)

c= [0 1 2 3 4 5 6 7 8 9]


In [11]:
d=np.linspace(0,2,11) #等分等差
d

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [12]:
e=np.ones((3,3))#全1
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
f=np.zeros((3,6)) #全零
f

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
g=np.eye(4) #对角
g

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
h=np.random.randn(6,4) #正态分布  随机数据
h

array([[ 0.4284025 ,  0.44226236,  0.20699878,  0.58233235],
       [-0.27104021,  0.99923483,  1.27480766,  1.16939074],
       [ 1.00886989, -0.09499028, -0.73351817,  1.28010414],
       [-0.14613268,  0.43298273, -1.15006542,  0.32159633],
       [ 1.16457115,  0.10185805, -0.27980038,  2.48373478],
       [-0.5319578 , -0.72988856, -0.74536738,  0.10311694]])

In [16]:
a = np.arange(10)
print(a[0],a[3],a[-1])

0 3 9


In [17]:
a[:4]

array([0, 1, 2, 3])

In [18]:
a[3:7]

array([3, 4, 5, 6])

In [19]:
a[6:]

array([6, 7, 8, 9])

In [20]:
a[2:8:2]

array([2, 4, 6])

In [21]:
a[2::2]

array([2, 4, 6, 8])

In [22]:
a[::3]

array([0, 3, 6, 9])

In [23]:
a=np.arange(0,51,10).reshape(6,1)+np.arange(6)


In [26]:
np.arange(0,51,10)

array([ 0, 10, 20, 30, 40, 50])

In [27]:
np.arange(0,51,10).reshape(6,1)

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [29]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [30]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [31]:
a[0,0]

0

In [32]:
a[2,-1]

25

In [33]:
a[:3,3:]

array([[ 3,  4,  5],
       [13, 14, 15],
       [23, 24, 25]])

In [34]:
a[2,:]

array([20, 21, 22, 23, 24, 25])

In [35]:
a[:,3]

array([ 3, 13, 23, 33, 43, 53])

In [36]:
a[:,::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24],
       [30, 32, 34],
       [40, 42, 44],
       [50, 52, 54]])

In [37]:
a[::2,::3]

array([[ 0,  3],
       [20, 23],
       [40, 43]])

## 数组和标量运算

In [38]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [39]:
a+5
b=np.random.randint(1,5,20)
b

array([2, 4, 1, 3, 3, 1, 4, 4, 2, 2, 4, 1, 2, 2, 1, 1, 1, 1, 1, 1])

In [40]:
c=b.reshape(4,5)
c

array([[2, 4, 1, 3, 3],
       [1, 4, 4, 2, 2],
       [4, 1, 2, 2, 1],
       [1, 1, 1, 1, 1]])

In [41]:
c*3

array([[ 6, 12,  3,  9,  9],
       [ 3, 12, 12,  6,  6],
       [12,  3,  6,  6,  3],
       [ 3,  3,  3,  3,  3]])

## 数组和数组之间的运算 

In [42]:
a=np.random.random_integers(1,5,(5,4))
a

<ipython-input-42-e75396ad7a76>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  a=np.random.random_integers(1,5,(5,4))


array([[5, 3, 3, 4],
       [1, 4, 2, 4],
       [3, 5, 4, 5],
       [5, 4, 4, 4],
       [2, 2, 5, 3]])

In [43]:
b=np.ones((5,4),dtype=int)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [44]:
a+b

array([[6, 4, 4, 5],
       [2, 5, 3, 5],
       [4, 6, 5, 6],
       [6, 5, 5, 5],
       [3, 3, 6, 4]])

In [45]:
c=np.random.random_integers(1,5,(3,4))
c

<ipython-input-45-708e4fb353cc>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  c=np.random.random_integers(1,5,(3,4))


array([[1, 5, 1, 3],
       [4, 5, 3, 1],
       [3, 1, 1, 3]])

In [46]:
d=np.random.random_integers(1,5,(3,4))
d

<ipython-input-46-7524c3ddfea8>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  d=np.random.random_integers(1,5,(3,4))


array([[2, 4, 3, 1],
       [2, 3, 2, 2],
       [5, 2, 3, 5]])

In [47]:
c*d

array([[ 2, 20,  3,  3],
       [ 8, 15,  6,  2],
       [15,  2,  3, 15]])

## 矩阵的内积运算 

In [48]:
a=np.random.random_integers(1,5,(3,2))
a

<ipython-input-48-51cc0ec12a28>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  a=np.random.random_integers(1,5,(3,2))


array([[4, 3],
       [1, 4],
       [2, 2]])

In [49]:
b=np.random.random_integers(1,5,(2,3))
b

<ipython-input-49-8e96a18d0bad>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  b=np.random.random_integers(1,5,(2,3))


array([[1, 5, 4],
       [2, 5, 2]])

In [50]:
np.dot(a,b)

array([[10, 35, 22],
       [ 9, 25, 12],
       [ 6, 20, 12]])

## 数组的比较运算

In [51]:
a=np.array([1,2,3,4])
b=np.array([4,2,2,4])
print(a==b)
print(a>b)
print((a==b).all())
print((a==b).any())

[False  True False  True]
[False False  True False]
False
True


## 数组的内置函数 

In [54]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [55]:
np.cos(a)#余弦

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219])

In [56]:
np.exp(a)#指数

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [57]:
np.sqrt(a)#平方根

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

## 一维数组 

In [58]:
a=np.random.random_integers(1,5,6)
a

<ipython-input-58-9c482f6fd4d3>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  a=np.random.random_integers(1,5,6)


array([3, 5, 5, 2, 5, 4])

In [59]:
a.sum()

24

In [60]:
a.mean()

4.0

In [61]:
a.std()#标准差

1.1547005383792515

In [62]:
a.min()

2

In [63]:
a.max()

5

In [64]:
a.argmin()#最小值索引

3

In [65]:
a.argmax()

1

## 二维数组 

In [66]:
b=np.random.random_integers(1,5,(6,4))
b

<ipython-input-66-177b021f1b27>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  b=np.random.random_integers(1,5,(6,4))


array([[5, 2, 5, 1],
       [3, 4, 2, 3],
       [4, 1, 4, 3],
       [5, 5, 2, 5],
       [4, 1, 5, 2],
       [4, 2, 4, 4]])

In [67]:
b.sum()

80

In [68]:
b.sum(axis=0)

array([25, 15, 22, 18])

In [69]:
b.sum(axis=1)

array([13, 12, 12, 17, 12, 14])

In [70]:
b.sum(axis=1).sum()

80

In [71]:
b.min(axis=1)

array([1, 2, 1, 2, 1, 2])

In [72]:
b.argmin(axis=1)

array([3, 2, 1, 2, 1, 1], dtype=int64)

In [73]:
b.std(axis=1)

array([1.78535711, 0.70710678, 1.22474487, 1.29903811, 1.58113883,
       0.8660254 ])

## 数组维度变换

In [74]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [75]:
b=np.arange(4,3)
b

array([], dtype=int32)

In [76]:
b.ravel()

array([], dtype=int32)

In [77]:
a= np.arange(4)
a

array([0, 1, 2, 3])

In [78]:
a.shape

(4,)

In [79]:
b=a[:,np.newaxis]
b

array([[0],
       [1],
       [2],
       [3]])

In [80]:
b.shape

(4, 1)

In [81]:
c=a[np.newaxis,:]
c

array([[0, 1, 2, 3]])

In [83]:
c.shape

(1, 4)

## 数组的排序及索引 

In [84]:
a=np.random.random_integers(1,10,(6,4))
a

<ipython-input-84-18b3b3b733c1>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  a=np.random.random_integers(1,10,(6,4))


array([[ 5,  5,  8,  7],
       [ 1,  1,  4,  1],
       [ 3, 10,  5,  5],
       [ 1,  6,  7,  7],
       [ 2,  2,  8, 10],
       [ 7,  4,  6,  4]])

In [85]:
b=np.sort(a,axis=1)#按行
b

array([[ 5,  5,  7,  8],
       [ 1,  1,  1,  4],
       [ 3,  5,  5, 10],
       [ 1,  6,  7,  7],
       [ 2,  2,  8, 10],
       [ 4,  4,  6,  7]])

In [86]:
a.sort(axis=0)#按列
a

array([[ 1,  1,  4,  1],
       [ 1,  2,  5,  4],
       [ 2,  4,  6,  5],
       [ 3,  5,  7,  7],
       [ 5,  6,  8,  7],
       [ 7, 10,  8, 10]])

In [91]:
a=np.random.random_integers(1,10,6)
a

<ipython-input-91-fa04500186dd>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  a=np.random.random_integers(1,10,6)


array([ 1, 10,  3,  2,  4,  5])

In [93]:
idx = a.argsort()
print(idx)

[0 3 2 4 5 1]


In [94]:
a[idx]#虚拟排序后

array([ 1,  2,  3,  4,  5, 10])

In [95]:
b=a[idx]
b

array([ 1,  2,  3,  4,  5, 10])

## 文件操作 

In [96]:
a=np.arange(15).reshape(3,5)
np.savetxt("test.txt",a)

In [97]:
b=np.loadtxt("test.txt")
b

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [98]:
np.save("test.npy",a)

In [99]:
c=np.load("test.npy")
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])